export const SEARCH_TERM_ENTERED = "SEARCH_TERM_ENTERED";
export const SEARCH_TERM = "SEARCH_TERM";
export const CATEGORY_SELECTED = "CATEGORY_SELECTED";
export const LINK_SELECTED = "LINK_SELECTED";
export const CONTACTING = "CONTACTING";